
// Include important C++ libraries here
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <iostream>
#include <sstream>
#include <vector>

// change the size here
#define NUM_VERTICES 3		// Credit: Eric

//Make the code easier to type with "using namespace"
using namespace sf;
using namespace std;

// Generate random number between 1 and NUM_VERTICES inclusive
int GenerateRandomNumber()// Credit: Isaac
{
	int randomNumber = rand() % NUM_VERTICES;
	return randomNumber;
}

// Calulate the midpoint between the user point and the designated random point
Vector2f GenerateMidpoint(Vector2f userPoint, Vector2f randomPoint)		// Credit: Eric
{
	Vector2f midPoint;

	midPoint.x = (userPoint.x + randomPoint.x) / 2;
	midPoint.y = (userPoint.y + randomPoint.y) / 2;

	return midPoint;
}

int main()
{
	// Create a video mode object
	VideoMode vm(1920, 1080);
	// Create and open a window for the game
	RenderWindow window(vm, "Chaos Game!!", Style::Default);
	
	vector<Vector2f> vertices;
	vector<Vector2f> points;

    Font font;

    if(!font.loadFromFile("/usr/share/fonts/truetype/ubuntu/UbuntuSans[wdth,wght].ttf"))
    {
        if (!font.loadFromFile("C:/Windows/Fonts/arial.ttf"))							// Credit: Isaac
		{
			cout << "Unable to load font from memory" << endl;
			return -1;
		}
    }

	Text userText;
	userText.setFont(font);							// Credit: Isaac
	userText.setCharacterSize(24);

	switch(NUM_VERTICES)
	{
		case 3:
			userText.setString("Please complete your triangle");
			break;
		case 4:
			userText.setString("Please complete your square");			// Credit: Eric
			break;
		case 5:
			userText.setString("Please complete your pentagon");
			break;
		default:
			return -1;
	}
    
	userText.setFillColor(Color::White);		// Credit: Isaac
	userText.setPosition(150, 50);

	int randomVertexIndex = GenerateRandomNumber();
	int previousrandomVertexIndex = (vertices.size() == 5) ? randomVertexIndex : GenerateRandomNumber();

	srand(time(NULL));

	// for(int i = 0; i < 5; i++)
	// {
	// 	randomVertexIndex = GenerateRandomNumber();
	// 	cout << randomVertexIndex << endl;
	// }

	while (window.isOpen())
	{
		/*
		****************************************
		Handle the players input
		****************************************
		*/

		Event event;
		while (window.pollEvent(event))
		{
		    if (event.type == Event::Closed)
		    {
				// Quit the game when the window is closed
				window.close();
		    }
		    if (event.type == sf::Event::MouseButtonPressed)
		    {
				if (event.mouseButton.button == sf::Mouse::Left)
				{
					std::cout << "the left button was pressed" << std::endl;
					std::cout << "mouse x: " << event.mouseButton.x << std::endl;
					std::cout << "mouse y: " << event.mouseButton.y << std::endl;
		
					if(vertices.size() < NUM_VERTICES)
					{
						vertices.push_back(Vector2f(event.mouseButton.x, event.mouseButton.y));
					}
					else if(points.size() == 0)
					{
						///fourth click
						///push back to points vector
						points.push_back(Vector2f(event.mouseButton.x, event.mouseButton.y));	// Credit: Isaac
					}
				}
		    }
		}
		if (Keyboard::isKeyPressed(Keyboard::Escape))
		{
			window.close();
		}
		/*
		****************************************
		Update
		****************************************
		*/
	
		if(points.size() > 0)
		{
		    ///generate more point(s)
		    ///select random vertex
		    ///calculate midpoint between random vertex and the last point in the vector
		    ///push back the newly generated coord.
			Vector2f midPoint;																			// Credit: Isaac
			// Reminder: GenerateRandomNumber() generates random number between 1 and 3 inclusive
			while(points.size() < 20000)	//	<-- Number of points generated by the program
			{
				randomVertexIndex = GenerateRandomNumber();
				if(vertices.size() == 4)
				{
					while(randomVertexIndex == previousrandomVertexIndex)		// Credit: Eric extra credit square
					{
						randomVertexIndex = GenerateRandomNumber();
					}
				}
				else if(vertices.size() == 5)
				{
					// previousrandomVertexIndex = randomVertexIndex;
					int sum = (previousrandomVertexIndex + 1) % 5;
					int difference = (((previousrandomVertexIndex - 1) % 5) + 5) % 5;
					while(randomVertexIndex == sum || randomVertexIndex == difference)
					{
						randomVertexIndex = GenerateRandomNumber();				// Credit: Eric extra credit pentagon
						// cout << endl;
						// cout << "sum: " << sum << endl;
						// cout << "difference: " << difference << endl;
						// cout << "randomVertexIndex: " << randomVertexIndex << endl;
						// cout << endl;
					}
					// cout << "done iterating randomVertexIndex" << endl;
					// cout << "sum: " << sum << endl;
					// cout << "difference: " << difference << endl;
					// cout << "randomVertexIndex: " << randomVertexIndex << endl;
					// cout << endl;
					// cout << "sum: " << sum << endl;
					// cout << "difference: " << difference << endl;
					// cout << "randomVertexIndex: " << randomVertexIndex << endl;
					// cout << endl;
				}
				if(vertices.size() > 3)// Credit: Eric: Triangle
				{
					previousrandomVertexIndex = randomVertexIndex;
				}
				
				// cout << "\nrandomVertexIndex:\n";
				// cout << "------------------\n";
				// cout << randomVertexIndex << "\n\n";

				midPoint = GenerateMidpoint(points[points.size() - 1], vertices[randomVertexIndex]); // Credit: Isaac

				// cout << "midPoint:\n";
				// cout << "---------\n";
				// cout << "(" << midPoint.x << ", " << midPoint.y << ")\n";

				// cout << "\nvertices[" << randomVertexIndex << "]:\n";
				// cout << "------------\n";
				// cout << "(" << vertices[randomVertexIndex].x << ", " << vertices[randomVertexIndex].y << ")\n";

				points.push_back(midPoint); // Credit: Isaac
			}
		}
	
		/*
		****************************************
		Draw
		****************************************
		*/
		window.clear();
		for(size_t i = 0; i < vertices.size(); i++)
		{
		    RectangleShape rect(Vector2f(10,10));
		    rect.setPosition(Vector2f(vertices[i].x, vertices[i].y));
		    rect.setFillColor(Color::Blue);
		    window.draw(rect);
		}
		///TODO:  Draw points
		for(size_t i = 0; i < points.size(); i++)// Credit: Isaac
		{
			RectangleShape rect(Vector2f(10, 10));
			rect.setPosition(Vector2f(points[i].x, points[i].y));
			if(i == 0)
			{
				//	The color of the point the user clicks is yellow
				rect.setFillColor(Color::Yellow);
			}
			else
			{
				//	The colors the points the computer generates are red
				rect.setFillColor(Color::Red);
			}
			window.draw(rect);
		}
		window.draw(userText);
		window.display();
	}
}
